### ISSUE TITLE
Does this work with SpringBoot 2.4.x?

### ISSUE THREAD

**Issue by arsalans** [bwaldvogel/mongo-java-server#182] opened 2021-03-29 14:45 UTC
SpringBoot 2.4.x uses Mongo Driver 4.x and they have different packages for Mongo classes. Will this work with that version of SpringBoot?

**Comment by bwaldvogel** [comment] 2021-04-08 07:12
mongo-java-server implements the wire protocol and does not depend on the actual Java driver package structure. mongo-java-server even works with drivers of other languages such as the Javascript client. However, it’s not part of the integration test suite and neither do we currently tests with multiple versions of the Mongo Java Driver.

Feel free to give it a try by yourself and report issues that you might find or even better, submit a pull request to fix the issues ;)

**Comment by pancakeslp** [comment] 2021-07-14 16:21
Not an issue, just an FYI

I'm using spring boot 2.5.2 and it seems to work (upgraded from 2.2.5-RELEASE to 2.5.2  this week)

as a maven dependency it looks like
```
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-mongodb</artifactId>
                <version>2.5.2</version>
            </dependency>
```
I'm able to use bwaldvogel/mongo-java-server v1.26.0 and v 1.38.0 with spring boot v2.5.2


using the maven dependency tree command ` mvn dependency:tree ` (snippet below) you can see we are using mongo driver 4.2.3

```
[INFO] +- org.springframework.boot:spring-boot-starter-data-mongodb:jar:2.5.2:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.5.2:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.5.2:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.5.2:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.28:compile
[INFO] |  +- org.mongodb:mongodb-driver-sync:jar:4.2.3:compile
[INFO] |  |  +- org.mongodb:bson:jar:4.2.3:compile
[INFO] |  |  \- org.mongodb:mongodb-driver-core:jar:4.2.3:compile
[INFO] |  \- org.springframework.data:spring-data-mongodb:jar:3.2.2:compile
[INFO] |     +- org.springframework:spring-tx:jar:5.3.8:compile
[INFO] |     +- org.springframework:spring-expression:jar:5.3.8:compile
[INFO] |     \- org.springframework.data:spring-data-commons:jar:2.5.2:compile
```


Probably going off topic now ... I did have a few issues with the spring beans when I upgraded to spring boot 2.5.2 thus why I found this issue.
But the cause of my problems was 
* things had been renamed in mongo driver 4.x
* I still had some dependencies for mongo driver 3.x which caused conflicts

**Comment by bwaldvogel** [comment] 2021-07-19 13:37
@pancakeslp: Thanks for this comment! This might help other developers in the future.

Closing this issue.

**Closed by bwaldvogel** 2021-07-19 13:37 UTC
