### ISSUE TITLE
MongoIncompatibleDriverException after update to spring-boot 3.4.0

### ISSUE THREAD

**Issue by Petar-Dimitrov-AXA** [bwaldvogel/mongo-java-server#235] opened 2024-12-16 15:17 UTC
After I updated the version of the spring-boot dependency to 3.4.0 I got the following exception: 
**org.springframework.data.mongodb.MongoIncompatibleDriverException: Server at 127.0.0.1:62931 reports wire version 6, but this version of the driver requires at least 7 (MongoDB 3.6).**
**

Is this know issue and will it be fixed?

**Comment by bwaldvogel** [comment] 2024-12-29 17:19
I just released version `1.46.0` which bumps the wire protocol version to `7`. Please let me know if this works in your case.

**Comment by bwaldvogel** [comment] 2024-12-29 17:20
I’m closing this since this is actually a duplicate of https://github.com/bwaldvogel/mongo-java-server/issues/233

**Closed by bwaldvogel** 2024-12-29 17:20 UTC
