### ISSUE TITLE
Error running query

### ISSUE THREAD

**Issue by adevore3** [bwaldvogel/mongo-java-server#77] opened 2019-06-28 17:26 UTC
Is the command `query` not implemented? Or maybe it's the `count` or `$ne` operator?

`com.mongodb.MongoCommandException: Command failed with error 59 (CommandNotFound): 'no such command: '$query'' on server localhost:44435. The full response is {"$err": "no such command: '$query'", "errmsg": "no such command: '$query'", "code": 59, "codeName": "CommandNotFound", "bad cmd": {"$query": {"count": "lookbackReqState", "query": {"state": {"$ne": "DONE"}}}, "$readPreference": {"mode": "nearest"}}, "ok": 0}`

**Comment by bwaldvogel** [comment] 2019-07-16 19:25
Closing as duplicate of #78

**Closed by bwaldvogel** 2019-07-16 19:25 UTC

**Comment by bwaldvogel** [comment] 2019-07-16 20:44
Version `1.17.0` contains the fix.
